name: Compile Sketches

on:
  - push
  - pull_request

jobs:
  compile-sketches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # See: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketches
        uses: arduino/compile-sketches@v1
        with:
          fqbn: esp32:esp32:esp32
          sketch-paths: |
            - examples/GamepadExamples/CharacteristicsConfiguration/CharacteristicsConfiguration.ino
            - examples/GamepadExamples/DrivingControllerTest/DrivingControllerTest.ino
            - examples/GamepadExamples/FlightControllerTest/FlightControllerTest.ino
            - examples/GamepadExamples/Gamepad/Gamepad.ino
            - examples/GamepadExamples/IndividualAxes/IndividualAxes.ino
            - examples/GamepadExamples/Keypad4x4/Keypad4x4.ino
            - examples/GamepadExamples/MultipleButtonsAndHats/MultipleButtonsAndHats.ino
            - examples/GamepadExamples/MultipleButtonsDebounce/MultipleButtonsDebounce.ino
            - examples/GamepadExamples/MultipleButtons/MultipleButtons.ino
            - examples/GamepadExamples/PlayerIndicators/PlayerIndicators.ino
            - examples/GamepadExamples/PotAsAxis/PotAsAxis.ino
            - examples/GamepadExamples/SingleButtonDebounce/SingleButtonDebounce.ino
            - examples/GamepadExamples/SingleButton/SingleButton.ino
            - examples/GamepadExamples/SpecialButtons/SpecialButtons.ino
            - examples/GamepadExamples/TestAll/TestAll.ino
            - examples/GamepadExamples/XboxXInputController/XboxXInputController.ino
            - examples/KeyboardExamples/KeyboardLEDs/KeyboardLEDs.ino
            - examples/KeyboardExamples/MediaKeys/MediaKeys.ino
            - examples/KeyboardExamples/PressKey/PressKey.ino
            - examples/MultipleDeviceExamples/DeferredReports/DeferredReports.ino
            - examples/MultipleDeviceExamples/GamepadAndMouse/GamepadAndMouse.ino
            - examples/MultipleDeviceExamples/GamepadMouseKeyboard/GamepadMouseKeyboard.ino
            - examples/MultipleDeviceExamples/MouseAndKeyboard/MouseAndKeyboard.ino            
          libraries: |
            - name: callback
            - name: NimBLE-Arduino
            - source-path: .
